### ISSUE TITLE
Comparison to other solutions (e.g. Yugabyte DB)

### ISSUE THREAD

**Issue by cdhagmann** [orioledb/orioledb#14]
As all the information provided is in the README, I am having a problem comparing it with other options. Is that something that you could possible provide?

**Comment by postgresnx** [comment]
OrioleDB is a storage engine designed to integrate into Postgres via the Table Access Method framework which is a standardized API framework. OrioleDB requires certain additional hooks in this API to operate. These additional API will be submitted for incorporation into future versions of Postgres. For now, please refer to this distro for these API additions. 

https://github.com/orioledb/postgres

**Comment by NikolayS** [comment]
Alexander's presentation should be helpful:

- https://vimeo.com/649616139
- https://www.slideshare.net/AlexanderKorotkov/solving-postgresql-wicked-problems
