### ISSUE TITLE
ERROR:  cache lookup failed for type 0

### ISSUE THREAD

**Issue by Tanyaevm** [orioledb/orioledb#149]
sql/test.sql:

Tested on [github_issue_135](https://github.com/orioledb/orioledb/tree/github_issue_135)

Error with orioledb:
```sql
CREATE EXTENSION IF NOT EXISTS orioledb;
CREATE TABLE o_test_1(
    val_1 int,
    val_2 int, 
    val_3 int,
    CONSTRAINT const1 PRIMARY KEY(val_1,val_2) 
)USING orioledb;
SELECT * FROM o_test_1 WHERE (val_1,val_2,val_3) < (10,1,1) LIMIT 1;
--ERROR:  cache lookup failed for type 0
```

Run as:
```
make regresscheck USE_PGXS=1 REGRESSCHECKS="test"
```

**Comment by homper** [comment]
Just for the note: also reproduced on [alter_type_using](https://github.com/orioledb/orioledb/tree/alter_type_using)

**Comment by homper** [comment]
Fixed on [alter_type_using](https://github.com/orioledb/orioledb/tree/alter_type_using)
Added row search key support
