### ISSUE TITLE
Exclusion index doesn't work

### ISSUE THREAD

**Issue by Tanyaevm** [orioledb/orioledb#155]
sql/test.sql:

Tested on [github_issue_135](https://github.com/orioledb/orioledb/tree/github_issue_135)

```sql
CREATE EXTENSION IF NOT EXISTS orioledb;
CREATE TABLE o_test_1(
    val_1 int,
    val_2 int,
    val_3 int,
    val_4 int,
  EXCLUDE USING btree (val_1 WITH =)
)USING orioledb;
INSERT INTO o_test_1 VALUES (1, 2, 3, 4);
INSERT INTO o_test_1 VALUES (1, 5, 6, 7);
```

Error postgres:
```sql
ERROR:  conflicting key value violates exclusion constraint "o_test_1_val_1_excl"
DETAIL:  Key (val_1)=(1) conflicts with existing key (val_1)=(1).
```
With orioledb no error

Run as:
```
make regresscheck USE_PGXS=1 REGRESSCHECKS="test"
```

**Comment by akorotkov** [comment]
At first, let's just correctly notify that we don't support exclusion constraints.

**Comment by homper** [comment]
Fixed on [github_issue_155](https://github.com/orioledb/orioledb/tree/github_issue_155) by adding message "exclusion indices are not supported."
