### ISSUE TITLE
orioledb_undo catalog grows steadily till the disk space is run out during a pgbench init procedure

### ISSUE THREAD

**Issue by vbp1** [orioledb/orioledb#18]
Steps to reproduce:

/usr/local/pgsql/bin/initdb --wal-segsize=128 /pg_data
cp ./orioledb-test/postgresql.auto.conf /pg_data/

/usr/local/pgsql/bin/pg_ctl -D /pg_data start
/usr/local/pgsql/bin/pgbench -i -I d
/usr/local/pgsql/bin/psql -f orioledb-test/pgbench.sql
/usr/local/pgsql/bin/pg_ctl -D /pg_data stop

mv /pg_data/orioledb_undo /pg_wal/
mv /pg_data/pg_wal /pg_wal/
ln -s /pg_wal/orioledb_undo /pg_data/orioledb_undo
ln -s /pg_wal/pg_wal /pg_data/pg_wal

/usr/local/pgsql/bin/pg_ctl -D /pg_data start

export PGPASSWORD='password'
/usr/local/pgsql/bin/pgbench -i -I gvp -s 75000 -U pgbench -h 127.0.0.1 pgbench

…
pgbench: fatal: PQputline failed(92%) done (elapsed 17690.38 s, remaining 1385.41 s)

$ df -h | grep -e pg_data -e pg_wal -e Filesystem

Filesystem                      Size  Used Avail Use% Mounted on
/dev/nvme0n1                    1.5T 1002G  488G  68% /pg_data
/dev/nvme1n1                    1.5T  1.5T   24K 100% /pg_wal

$ du --max-depth=1 -h

1.4T    ./orioledb_undo
69G     ./pg_wal
1.5T    .
Let's see a postgres log:
2022-03-09 23:34:15 MSK [61541]: [2-1] us=,db=,app=,cli= PANIC:  could not write buffer to file orioledb_undo/00000058BA
2022-03-09 23:34:15 MSK [61456]: [9-1] us=,db=,app=,cli= LOG:  background worker "orioledb background writer" (PID 61541) was terminated by signal 6: Aborted
2022-03-09 23:34:15 MSK [61456]: [10-1] us=,db=,app=,cli= LOG:  terminating any other active server processes
2022-03-09 23:34:17 MSK [61456]: [11-1] us=,db=,app=,cli= LOG:  all server processes terminated; reinitializing

 orioledb specific settings in the postgresql.auto.conf (server: 2 sockets, 36 physical cores total, 256GB RAM):
orioledb.main_buffers = 16GB
orioledb.free_tree_buffers = 256MB
orioledb.catalog_buffers = 256MB
orioledb.undo_buffers = 1GB
orioledb.recovery_pool_size = 14
orioledb.recovery_queue_size = 64MB
orioledb.checkpoint_completion_ratio = 0.9
orioledb.bgwriter_num_workers = 8
orioledb.max_io_concurrency = 64

pgbench.sql:

CREATE EXTENSION IF NOT EXISTS orioledb WITH SCHEMA public;
COMMENT ON EXTENSION orioledb IS 'OrioleDB -- the next generation transactional engine';

CREATE USER pgbench WITH PASSWORD 'password';
CREATE DATABASE  pgbench;
ALTER DATABASE pgbench OWNER TO pgbench;

\c pgbench

CREATE EXTENSION IF NOT EXISTS orioledb WITH SCHEMA public;
COMMENT ON EXTENSION orioledb IS 'OrioleDB -- the next generation transactional engine';

SET ROLE pgbench;

SET default_tablespace = '';
SET default_table_access_method = orioledb;

CREATE TABLE public.pgbench_accounts (
    aid int8 NOT NULL,
    bid int8,
    abalance integer,
    filler character(84)
) USING orioledb
WITH (fillfactor='100', compress = 1, toast_compress = 5, primary_compress = -1);

ALTER TABLE public.pgbench_accounts OWNER TO pgbench;

CREATE TABLE public.pgbench_branches (
    bid int8 NOT NULL,
    bbalance integer,
    filler character(88)
) USING orioledb
WITH (fillfactor='100', compress = 1, toast_compress = 5, primary_compress = -1);

ALTER TABLE public.pgbench_branches OWNER TO pgbench;

CREATE TABLE public.pgbench_history (
    tid int8,
    bid int8,
    aid int8,
    delta integer,
    mtime timestamp without time zone,
    filler character(22)
) USING orioledb
WITH (compress = 1, toast_compress = 5, primary_compress = -1);

ALTER TABLE public.pgbench_history OWNER TO pgbench;

CREATE TABLE public.pgbench_tellers (
    tid int8 NOT NULL,
    bid int8,
    tbalance integer,
    filler character(84)
) USING orioledb
WITH (fillfactor='100', compress = 1, toast_compress = 5, primary_compress = -1);

ALTER TABLE public.pgbench_tellers OWNER TO pgbench;

**Comment by ioxgrey** [comment]
I am wonder too about this undo growing during COPY statement. Does it really need all this undo?

**Comment by akorotkov** [comment]
Yes, in general COPY is lightweight version of INSERT.  And it needs cleanup on rollback in the same way as INSERT.
But check c6f0f3cf0c, it contains optimization for skipping undo for tables created or truncates in the current transaction.
Also, some notes regarding your scripts.
 * I would recommend to define tables with primary keys and then go with `-I gv`.  Defining a primary key makes OrioleDB reorganize the whole table.  It would be good economy of resources to evade this.
 * The option set `WITH (fillfactor='100', compress = 1, toast_compress = 5, primary_compress = -1)` actually leaves pgbench tables completely uncompressed.  pgbench tables doesn't have secondary indexes or toast, but consist of primary indexes.  In order to get these tables compressed, set `primary_compress` other than `-1`.
 * I would recommend to define `PRIMARY KEY(bid, mtime, tid, aid, delta)` for `pgbench_history` to lower concurrency for rightmost leaf page.

**Comment by akorotkov** [comment]
@vbp1, I'm looking forward hearing back from me if my recommendations help.

**Comment by akorotkov** [comment]
@vbp1, looks like a progress :) We'll investigate it further.

**Comment by vbp1** [comment]
> @vbp1, looks like a progress :) 
step by step:)

**Comment by ioxgrey** [comment]
Looks great!

```
pgbench -i -I gv -s 1000 postgres
generating data (client-side)...
100000000 of 100000000 tuples (100%) done (elapsed 231.07 s, remaining 0.00 s)
vacuuming...
done in 232.14 s (client-side generate 231.50 s, vacuum 0.64 s).
```
```
du -hs `ls` | grep oriole
13G     orioledb_data
60K     orioledb_undo
```

**Comment by vbp1** [comment]
@akorotkov, FYI:
pgbench=# vacuum analyze pgbench_accounts;
ERROR:  invalid memory alloc request size 1073741824


(gdb) b errfinish
Breakpoint 1 at 0x8d6910
(gdb) cont
Continuing.

Breakpoint 1, 0x00000000008d6910 in errfinish ()
(gdb) bt
#0  0x00000000008d6910 in errfinish ()
#1  0x00000000004e5794 in repalloc.cold ()
#2  0x00007ff17ffdce37 in load_next_in_memory_leaf_page () from /usr/local/pgsql/lib/orioledb.so
#3  0x00007ff17ffdd578 in make_btree_seq_scan_cb () from /usr/local/pgsql/lib/orioledb.so
#4  0x00007ff17ffdd614 in make_btree_sampling_scan () from /usr/local/pgsql/lib/orioledb.so
#5  0x00007ff18000358c in orioledb_acquire_sample_rows () from /usr/local/pgsql/lib/orioledb.so
#6  0x00000000005f463a in do_analyze_rel ()
#7  0x00000000005f5d61 in analyze_rel ()
#8  0x0000000000657251 in vacuum ()
#9  0x00000000006577c7 in ExecVacuum ()
#10 0x00000000007c9e60 in standard_ProcessUtility ()
#11 0x00007ff180043fd7 in pgss_ProcessUtility () from /usr/local/pgsql/lib/pg_stat_statements.so
#12 0x00007ff17ffe1dce in orioledb_utility_command () from /usr/local/pgsql/lib/orioledb.so
#13 0x00000000007c84cf in PortalRunUtility ()
#14 0x00000000007c8603 in PortalRunMulti ()
#15 0x00000000007c8b43 in PortalRun ()
#16 0x00000000007c4f6e in exec_simple_query ()
#17 0x00000000007c6701 in PostgresMain ()
#18 0x000000000074afe6 in ServerLoop ()
#19 0x000000000074bd98 in PostmasterMain ()
#20 0x00000000004e7a7d in main ()

**Comment by akorotkov** [comment]
@ioxgrey, thank you for checking!
@vbp1, thank you for the report and backtrace!  Should be fixed in 169525b5ea.

**Comment by vbp1** [comment]
> @ioxgrey, thank you for checking! @vbp1, thank you for the report and backtrace! Should be fixed in [169525b](https://github.com/orioledb/orioledb/commit/169525b5ead33927dd0f7ca1f7d8272508b3b784).

Issue looks like fixed. But I've got another issue now (#21). 
And I have some doubts about  c6f0f3c - maybe it turns off undo completely?

**Comment by ioxgrey** [comment]
I do some tests during pgbench workload.
Repeatable read results looks good

**Comment by vbp1** [comment]
> I do some tests during pgbench workload. Repeatable read results looks good
> 
> ```
> postgres=# BEGIN TRANSACTION ISOLATION LEVEL REPEATABLE READ;
> postgres=*# select count(1) from pgbench_history;
>   count  
> ---------
>  6104559
> (1 row)
> 
> postgres=*# select count(1) from pgbench_history;
>   count  
> ---------
>  6104559
> (1 row)
> 
> postgres=*# select count(1) from pgbench_history;
>   count  
> ---------
>  6104559
> (1 row)
> 
> postgres=*# select count(1) from pgbench_history;
>   count  
> ---------
>  6104559
> (1 row)
> 
> postgres=*# commit;
> COMMIT
> ```
> 
> Orioledb undo size looks reasonable too
> 
> ```
> du -hs `ls` | grep oriole
> 25G	orioledb_data
> 2.8G	orioledb_undo
> ```

Maybe you could check Repeatable Read and  Repeatable Read (for example tests from https://habr.com/ru/company/postgrespro/blog/467437/), if you have time and don't mind.

**Comment by akorotkov** [comment]
@vbp1, @ioxgrey, thank you for investigation!
The resolution regarding this issue looks so good so far.
Regarding #21, we're still working on it.

**Comment by vbp1** [comment]
Read Committed and Repeatable Read looks OK. I think we could close this issue. @akorotkov thank you.
