### ISSUE TITLE
More details of undo design 🚀

### ISSUE THREAD

**Issue by ezreal1997** [orioledb/orioledb#27]
First and foremost, I want to let you know that I think this engine is a **solid** work.

I've been following the in-place update engine of postgres for a long time. There was an implementation of in-place update engine called [[zheap](https://github.com/EnterpriseDB/zheap)](https://github.com/EnterpriseDB/zheap), which is incomplete and has met some issues.

It would be kind of you to show more details(detailed design doc, trade-off between space and performance, etc.) of your `undo` design and the difference between `orioledb` and `zheap`.

**Comment by postgresnx** [comment]
More details will be coming after June, but please reach out to Alexander via email for a private briefing. alexander@orioledb.com

**Comment by akorotkov** [comment]
See [architecture docs](https://github.com/orioledb/orioledb/blob/main/doc/arch.md).
