### ISSUE TITLE
Strict collation checks

### ISSUE THREAD

**Issue by akorotkov** [orioledb/orioledb#270]
* Allow usage only ICU collations in OrioleDB
 * Make stricter checks in pg_newlocale_from_collation(). Forbid usage of collations with versions mismatch.
 * Forbid `ALTER COLLATION ... REFRESH VERSION` when there are OrioleDB indexes using collation.
 * Document the changes.

**Comment by homper** [comment]
Implemented on [github_issue_270](https://github.com/orioledb/orioledb/tree/github_issue_270)
