### ISSUE TITLE
initdb failing with installcheck

### ISSUE THREAD

**Issue by MatheusFarias03** [orioledb/orioledb#273]
I'm trying to execute the installcheck command, but it fails due to not finding the initdb command. I've added my commands below:

* OS : Fedora 38
* Patch: 15_18
```
./configure --prefix=$(pwd) --enable-cassert --enable-debug CFLAGS="-ggdb -Og -g3"
make install
```
* OrioleDB: installation works fine.
```
make PG_CONFIG=~/Documents/PostgreSQL/PostgresOrioleDB/postgres/bin/pg_config  USE_PGXS=1 install
``` 

Now, make install:
```
+++ regress check in  +++
============== removing existing temp instance        ==============
============== creating temporary instance            ==============
============== initializing database system           ==============

pg_regress: initdb failed
```

* vim log/initdb.log:
```
sh: line 1: initdb: command not found
```

**Comment by homper** [comment]
You need to add postgres installation path to your PATH variable: 
--prefix argument of ./configure:
as I understand, it is: ~/Documents/PostgreSQL/PostgresOrioleDB/postgres/bin
```sh
export PATH=$HOME/Documents/PostgreSQL/PostgresOrioleDB/postgres/bin:$PATH
```

Also you may need to add this export it to your .bashrc if it doesn't conflict with existing postgres installation

**Comment by MatheusFarias03** [comment]
Thanks @homper , it worked here with the `export` command.
