### ISSUE TITLE
Different results SELECT UNLOGGED TABLE

### ISSUE THREAD

**Issue by Tanyaevm** [orioledb/orioledb#316]
Tested on [main](https://github.com/orioledb/orioledb/tree/main)
Commit 63244571c15d8b59e73bc7caf201bd18c0c971bf

t/example_test.py:

```py
def test_1(self):
		node = self.node
		node.start()

		node.safe_psql("""

			CREATE EXTENSION IF NOT EXISTS orioledb;
			
			CREATE UNLOGGED TABLE o_test_1(
				val_1 serial PRIMARY KEY, 
				val_2 int, 
				val_3 int, 
				val_4 int
			)USING orioledb;
				 
			INSERT INTO o_test_1 (val_1, val_2, val_3) VALUES (1,2,3);
				 			
			CHECKPOINT;
	
		""")

		node.stop(['-m', 'immediate'])

		node.start()

		print(node.safe_psql("""
				 SELECT * FROM o_test_1;
				 """))

		node.stop()

```

**Expected result print**
```sql
b''
```
**Actual result print with orioledb**
```sql
b'1|2|3|\n'
```

Run as:
```
make USE_PGXS=1 testgrescheck_part_1 TESTGRESCHECKS_PART_1="t.example_test.TestClass.test_1"
```

Where:
- **t** - folder with python tests
- **example_test** - test file name
- **TestClass** - test class name
- **test_1** - test name

**Comment by homper** [comment]
Fixed on [github_issue_316](https://github.com/orioledb/orioledb/tree/github_issue_316)

**Comment by homper** [comment]
Now definitely fixed on [github_issue_316](https://github.com/orioledb/orioledb/tree/github_issue_316)
Сleanup was moved, so there should no longer be wal writing during recovery
