### ISSUE TITLE
bgwriter takes 100% cpu in s3 mode

### ISSUE THREAD

**Issue by pashkinelfe** [orioledb/orioledb#322]
I created 10K partitions and did inserts in the table by pgbench in 50 connections.

After ~100s inserts in s3 mode bgwriter process took 100% CPU
<img width="1127" alt="image" src="https://github.com/orioledb/orioledb/assets/63344111/33a9f4b1-165c-4c3c-87ea-f719de525cfb">

In s3-disabled mode bgwriter was ~1% CPU

TPS (s3) was ~32000, TPS (without s3) - ~30000, so bgwriter didn't slowed down concurrent inserts. But maybe performance could be even better if bgwriter tasks could be somehow optimized?

orioledb.s3_num_workers = 20

**Comment by pashkinelfe** [comment]
Flamegraph of bgwriter. 60 sec@ 1000 probes per second 
![bgwriter-concurrent-inserts](https://github.com/orioledb/orioledb/assets/63344111/c4ea207c-36e7-4634-b9a0-2459c160e1f4)

**Comment by akorotkov** [comment]
Please, recheck on main (234115c)

**Comment by pashkinelfe** [comment]
on https://github.com/orioledb/orioledb/commit/234115c782dd86b910a87cfd782bbec18d2f9361 I experience #333 and can not fill cluster with data
