### ISSUE TITLE
Tuples applied via logical receiver are not in S3 bucket after cluster stop

### ISSUE THREAD

**Issue by pashkinelfe** [orioledb/orioledb#342]
at e6b7425aaa79f7be4

Set logical replication from publisher pg cluster into subscriber orioledb+s3 cluster (for half of the tables, but this is not the point)
Insert ~5M rows into 100 partitions into the publisher cluster (pgdata ~4Gb)
Orioledb tables are propagated with tuples on the subscriber (50 tables, ~2.5M rows, pgdata ~2GB)
But the size in s3 bucket is much less before and after stopping the subscriber cluster.
Actual tuples are visible both on the publisher and subscriber. 

<img width="1549" alt="image" src="https://github.com/orioledb/orioledb/assets/63344111/c37bc4b3-4620-479c-b862-5d0abcfe4bc2">

```
orioledb-s3-prepare-logrepl.sh
orioledb-s3-insertonly-logrepl.sh
wait 500s
pg_ctl -D pgdatasubs stop 
```
[repl-reproduce.zip](https://github.com/orioledb/orioledb/files/14194598/repl-reproduce.zip)

After the second start of the subscriber and waiting for some time bucket size increases.
<img width="1482" alt="image" src="https://github.com/orioledb/orioledb/assets/63344111/0bdeeca7-98a0-4100-a566-c6da8aa9c69c">

**Comment by akorotkov** [comment]
Thank you, @pashkinelfe.
Could you list files with sizes within the orioledb_data directory and S3 bucket to compare?

**Comment by akorotkov** [comment]
```
s3: orioledb_data/1/5 (no files around 17020-17038)
```
This seems to be the problem.  Do you enable DEBUG1 messages in the log?  If so, are there attempts to put 17020-17038 files into orioledb_data/1/5?

**Comment by pashkinelfe** [comment]
@akorotkov I've mistaken. There are files in 1/5 (updated in the comment above)

**Comment by akorotkov** [comment]
Then, relation 17038 looks OK to me.
What is the exact size of S3 bucket?

**Comment by pashkinelfe** [comment]
At the point of last measurements
<img width="1136" alt="image" src="https://github.com/orioledb/orioledb/assets/63344111/0cb1ec70-b764-4a80-8d51-bb46a9822226">
I'll redo all the measurements after first cluster stop.

**Comment by akorotkov** [comment]
I also wonder why the data on the S3 bucket is so large? Could you check what is there?

**Comment by pashkinelfe** [comment]
Checking just after stopping subscriber cluster.
orioledb_data: local: 833M, s3: 791M

**Comment by akorotkov** [comment]
@pashkinelfe, thank you!

**Comment by pashkinelfe** [comment]
I suppose bloating of /data catalog on s3 due to undo is the same thing as https://github.com/orioledb/orioledb/issues/334
Nothing else left in this ticket so close it.
