### ISSUE TITLE
S3 Storage -> Enable multiple databases per bucket

### ISSUE THREAD

**Issue by olirice** [orioledb/orioledb#358]
## Context
Oriole's S3 backend currently maps 1 database to 1 S3 bucket.

AWS S3 supports up to 1000 buckets per account, which limits the number of databases that can be deployed in a single account for e.g. Postgres hosting providers.

## Feature Request

Add a configuration option for "path within bucket" to enable multiple database to store data in the same S3 bucket

---

Any thoughts on the security implications of multiple DBs in a single bucket?

**Comment by pashkinelfe** [comment]
Added by https://github.com/orioledb/orioledb/commit/74d02841358f06c716c5a3f7e72de7348c26a8b5
