### ISSUE TITLE
Error creating partitions declaratively on orioledb partitioned tables

### ISSUE THREAD

**Issue by pashkinelfe** [orioledb/orioledb#379]
Orioledb:  6e6856c49bc924afcb PG: patches17_3

```
CREATE TABLE IF NOT EXISTS messages_4 (id BIGSERIAL,
    inserted_at TIMESTAMP NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id, inserted_at)
) PARTITION BY RANGE (inserted_at) using orioledb;
CREATE TABLE
create table msg_4 PARTITION OF public.messages_4 for values FROM ('2024-10-01 00:00:00') TO ('2024-10-02 00:00:00');
ERROR:  could not open relation with OID 0
```

For heap tables works:
```
CREATE TABLE IF NOT EXISTS messages_5 (id BIGSERIAL,
    inserted_at TIMESTAMP NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id, inserted_at)
) PARTITION BY RANGE (inserted_at) using heap;
CREATE TABLE
create table msg_5 PARTITION OF public.messages_5 for values FROM ('2024-10-01 00:00:00') TO ('2024-10-02 00:00:00');
CREATE TABLE
```

Same behavior in modified regression test: https://github.com/orioledb/orioledb/commit/c94c5c9035b79db35d0f9c62802d42af48589764

**Comment by pashkinelfe** [comment]
Proposed fix https://github.com/orioledb/orioledb/commits/refs/heads/fix-partition-using-orioledb/

Notes on implementation:
PG16 doesn't support `create table .. PARTITION by ... USING orioledb' and outputs error
PG17 does support this and creates partitioned table (parent) with orioledb AM

Though if I use `set default_table_access_method = orioledb;`
and then `create table .. PARTITION by` no errors for PG16 and PG17 and partition table is created with heap AM. I'll modify tests accordingly.

**Comment by homper** [comment]
@pashkinelfe 
Fix looks good, tests changes also reasonable
Only executed pg_indent, and did a rebase
Could be merged

**Comment by pashkinelfe** [comment]
Merged, thanks!
