### ISSUE TITLE
Memory leak at tpc-c test

### ISSUE THREAD

**Issue by pashkinelfe** [orioledb/orioledb#380]
Orioledb 6e6856c49bc92  PG patches17_3

`initdb pgdata --no-locale`

config file:
```
statement_timeout = 0
shared_preload_libraries = orioledb
orioledb.main_buffers = 2GB
default_table_access_method = orioledb
```
(shared_buffers = 128M (default value))

Prepare:
`./bin/go-tpc tpcc prepare -d postgres -U parallels -p '5432' -D postgres -H 127.0.0.1 -P 5432 --conn-params sslmode=disable --no-check
`

At tpc-c test 
`./bin/go-tpc tpcc run -d postgres -U parallels -p '5432' -D postgres -H 127.0.0.1 -P 5432 --conn-params sslmode=disable -T 20 --time 20s --output table
`
Consumed memory increases to all available 8Gb and swapping occurs (pictures of intermediate state, then it increases more)
<img width="629" alt="image" src="https://github.com/user-attachments/assets/3d5c8af5-df0c-422e-9d74-cf2d1d83ecd5">
<img width="1302" alt="image" src="https://github.com/user-attachments/assets/26e5e708-ae53-4103-b421-1f901ce87ca1">

The same test on plain PG with 
```
statement_timeout = 0
shared_buffers = 2GB
```

shows stable memory consumption. Doesn't increase in the test.
<img width="802" alt="image" src="https://github.com/user-attachments/assets/c4f9e441-7565-4e74-b06d-c25986f440b0">

**Comment by pashkinelfe** [comment]
I have done inaccurate measurements, so close this.

**Comment by pashkinelfe** [comment]
This leak is not seen in pgbench test

```
pgbench -d postgres -i -s 100
pgbench -h localhost -d postgres -T50 -P10 -M prepared -c 10
```

<img width="849" alt="image" src="https://github.com/user-attachments/assets/60728052-c0d7-4290-a6ee-443f233cb068">

This could be a reason for difference in performance for pgbench (faster than heap) and tpc-c test (significantly slower than heap)

**Comment by pashkinelfe** [comment]
Backtraces:

**Comment by pashkinelfe** [comment]
I've bisected branch and found that 
The first commit with memory leak is 9183193f0b17d80d <Split functionality between table AM and index AM> with patches16_26
The last commit without memory leak is a2d90ae <Subscription simple test> with patches16_25

Patch between mentioned above 3cd9459e7f3db32 <Logical next xid> fails to build with patches16_26 or patches16_25.

**Comment by akorotkov** [comment]
@homper, could you, please, take a look?

**Comment by pashkinelfe** [comment]
I added https://github.com/orioledb/orioledb/tree/fix-memory-leak but this haven't fixed a leak

**Comment by pashkinelfe** [comment]
Checked at https://github.com/orioledb/orioledb/commit/0bfead4a075166a756bb66920625c766e8938533 There is no leak anymore
