### ISSUE TITLE
update docs for compression configuration options 

### ISSUE THREAD

**Issue by mdcallag** [orioledb/orioledb#393]
[The docs](https://www.orioledb.com/docs/usage/configuration) state that the compression options are
* orioledb.default_compress
* orioledb.primary_compress
* orioledb.toast_compress

But they should be:
* orioledb.default_compress
* orioledb.default_primary_compress
* orioledb.default_toast_compress

**Comment by pashkinelfe** [comment]
Thanks for reporting! Fixed as of cfdf353daece27313
