### ISSUE TITLE
Extensibility question

### ISSUE THREAD

**Issue by MichaelDBA** [orioledb/orioledb#9]
Can I Use Orioledb with PostgreSQL 14 binaries from PGDG?  Or do I have to compile PG with the extensibility package?

**Comment by akorotkov** [comment]
Sorry, PGDG binaries wouldn't work.  You have to use [PostgreSQL with extensibility patches](https://github.com/orioledb/postgres).

**Comment by MichaelDBA** [comment]
Thanks and keep up the incredible work!

**Comment by akorotkov** [comment]
Thank you!
